/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg.ipla;

import org.junit.Test;

import com.cg.ipla.dto.BowlingData;

import static org.junit.Assert.*;

import java.util.ArrayList;

public class IPLAnalyserTest {
	
	public static final String BOWLING_DATA="src/main/resources/WP DP Data_02 IPL2019FactsheetMostWkts.csv";
	public static final String BATTING_DATA="src/main/resources/WP DP Data_01 IPL2019FactsheetMostRuns.csv";
    @Test 
    public void getBowlingData_ShouldReturnLastEntry() {
    	IPLAnalyser iplAnalyser=new IPLAnalyser();
    	ArrayList<BowlingData> bowlersList=(ArrayList<BowlingData>) iplAnalyser.getBowlingDataFile(BOWLING_DATA);
    	System.out.println("BOWLERS LIST:");
    	iplAnalyser.printData(bowlersList);
    	assertEquals(100,bowlersList
    							.get(bowlersList.size()-1)
    							.getPosition());
    	
    }
    @Test
    public void getBattingData_ShouldReturnSize() {
    	IPLAnalyser iplAnalyser=new IPLAnalyser();
    	ArrayList<BowlingData> battersList=(ArrayList<BowlingData>) iplAnalyser.getBowlingDataFile(BATTING_DATA);
    	System.out.println("BATTERS LIST:");
    	iplAnalyser.printData(battersList);
    	assertEquals(99,battersList.size());
    	
    }
}
